global:
  domain: argocd.app.ismail-osman.co.uk
 
  

server: 
  service:
    type: ClusterIP 
  
  extraArgs:
    - --insecure
    
  

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: tls-cert-issuer 
      
      nginx.org/hosts: false
      
    hosts:
    - argocd.app.ismail-osman.co.uk

    tls:
    - secretName: argocd-server-tls
      hosts:
      - argocd.app.ismail-osman.co.uk
     

    
  
  

 