global:
  domain: argocd.app.ismail-osman.co.uk
  #default domain used by all components inside cluster
  

server: #argo cd API basically entrypoint to argocd 
  service:
    type: ClusterIP #service which sits in front of argocd pod
  
  extraArgs:
    - --insecure
    #No tls termination inside argo cd as nginx ingress controller already handles this
  
  #generating ingress resource for argo cd server
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: tls-cert-issuer 
      #this is read by cert-manager controller not argo cd which then requests a certificate and stores it in the secret specified in tls.secretname
      nginx.org/hosts: false
      #tells nginx ingress controller not to restrict traffic by hostname and to accept requests for any host. 
      #commonly used in environments where DNS set up is messy
    hosts:
    - argocd.app.ismail-osman.co.uk

    tls:
    - secretName: argocd-server-tls
      hosts:
      - argocd.app.ismail-osman.co.uk
      #Tells ingress controller which certificate to use for https and which hostname is must be valid for

    
  
  

 