crds:
  enabled: true 

extraArgs:
- --dns01-recursive-nameservers="8.8.8.8:53"
- --dns01-recursive-nameservers-only




serviceAccount:
  name: cert-manager 
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::598400998600:role/cert-manager"
