provider: aws

env:
- name: AWS_DEFAULT_REGION
  value: eu-west-2



serviceAccount:
  create: true 
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::598400998600:role/external-dns"


domainFilters:
- app.ismail-osman.co.uk
