apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: tls-cert-issuer 
spec:
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: "osy.ish2000@outlook.com"
    privateKeySecretRef:
      name: tls-cert-issuer
    solvers: 
    - dns01: 
        route53: 
          region: eu-west-2
          hostedZoneID: Z0075379YVJ2NJZFXYU
          
          
      selector:
        dnsZones:
        - "ismail-osman.co.uk"
    - http01:
        ingress:
          class: nginx

