
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ismail-deployment 
  
  labels:
    app: ismail-deployment 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ismail-deployment 
  template:
    metadata: 
      labels:
        app: ismail-deployment 
    spec:
      containers: 
      - name: game-app 
        image: 598400998600.dkr.ecr.eu-west-2.amazonaws.com/game-app:latest@sha256:2a743b4b337ccdef72ed98a1cb7e280dd843ca76a7e2c820e043b063ad94fee8
        ports:
        - containerPort: 3000

---


apiVersion: v1 
kind: Service
metadata:
  name: ismail-service 
spec:
  selector: 
    app: ismail-deployment 
  type: ClusterIP 
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: app-port 
    protocol: TCP 
    port: 8086 
    targetPort: 3000

---


apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata:
  name: ismail-ingress 
  
  annotations: 
    cert-manager.io/cluster-issuer: "tls-cert-issuer"
spec: 
  ingressClassName: nginx 
  tls: 
  - hosts: 
      - k8s.app.ismail-osman.co.uk
    secretName: my-secret 
  rules: 
  - host: k8s.app.ismail-osman.co.uk
    http: 
      paths: 
      - path: / 
        pathType: Prefix
        backend: 
          service: 
            name: ismail-service 
            port:
              number: 80
